#!/bin/sh
#shellcheck disable=SC1090

set -e
set -u

fn_help() { (
    a_user=${1:-}
    echo "pg-register-service v1.0.0 - registers an unprivileged postgres instance as the current user"
    echo ""
    echo "USAGE"
    echo "    pg-register-service <port> [user]"
    echo ""
    echo "EXAMPLE"
    echo "    pg-register-service 5432 ${a_user}"
    echo ""
    echo "COPYING"
    echo "    Copyright (c) 2024 AJ ONeal <aj@bnna.net>"
    echo "    Licensed under the MPL-2.0"
); }

g_pgport="${1:-}"
g_pguser="${2:-}"

if test -z "${g_pguser}"; then
    g_user="$(id -u -n)"
    g_pguser="${g_pguser:-$g_user}"
fi

if test -z "${g_pgport}"; then
    fn_help "${g_pguser}" >&2
    return 1
fi

if test "${g_pgport}" = "--help" ||
    test "${g_pgport}" = "help" ||
    test "${g_pgport}" = "-V" ||
    test "${g_pgport}" = "--version" ||
    test "${g_pgport}" = "version"; then
    fn_help "${g_pguser}" >&2
    return 0
fi

g_sudo=""
if command -v sudo > /dev/null; then
    g_sudo="sudo"
fi

fn_serviceman_find_or_install() { (
    if ! command -v systemctl > /dev/null; then
        return 0
    fi
    if ! command -v serviceman > /dev/null; then
        curl --fail-with-body -sS https://webi.sh/serviceman | sh
        . ~/.config/envman/PATH.env
    fi
); }

fn_init_local_db() { (
    mkdir -p ~/.local/share/postgres/var/run/

    # Default config at:
    #   /etc/postgresql/16/main/pg_hba.conf
    #   /etc/postgresql/16/main/postgresql.conf
    # Deafult data at: (also `SHOW data_directory;`)
    #   /var/lib/postgresql/16/main/

    echo "postgres" > ~/pg-pwfile.tmp
    initdb -D ~/.local/share/postgres/var/ \
        --username postgres --pwfile ~/pg-pwfile.tmp \
        --auth-local=password --auth-host=password
    rm ~/pg-pwfile.tmp
); }

fn_serviceman_add_pg() { (
    # if run as a login service:
    # sudo loginctl enable-linger "$(id -u -n)"

    ${g_sudo} env PATH="${PATH}" \
        serviceman add --name "postgres-as-${g_pguser}" --path "${PATH}" \
        --system --username "${g_user}" -- \
        postgres -D "${HOME}/.local/share/postgres/var" -p "${g_pgport}"
); }

main() { (
    fn_serviceman_find_or_install
    #echo '~'/.local/bin/serviceman

    fn_init_local_db
    #echo '~'/.local/share/postgres/var/

    fn_serviceman_add_pg
    #echo "/etc/systemd/system/postgres-as-${g_pguser}.service"
); }
main
