#!/bin/sh
set -e
set -u

g_version="v1.0.1"

fn_help() { (
    echo "psql-backup ${g_version} - creates portable (across instances) SQL schema & data backups"
    echo ""
    echo "USAGE"
    echo "    psql-backup <user> [host] [port] [dbname]"
    echo ""
    echo "EXAMPLE"
    echo "    psql-backup 'foobar-xxxxxx' 'pg-1.example.com' 5432 'foobar-xxxxxx'"
    echo ""
    echo "NOTES"
    echo "    - the username and database name should typically be the same"
    echo ""
    echo "COPYING"
    echo "    Copyright (c) 2024 AJ ONeal <aj@bnna.net>"
    echo "    Licensed under the MPL-2.0"
); }

fn_pg_dump_parts() { (
    b_user="${1}"
    b_host="${2}"
    b_port="${3}"
    b_db="${4}"

    if test "${b_port}" = 443; then
        export PGSSLMODE=require
        export PGSSLNEGOTIATION=direct
    fi

    # Note: schema includes extensions such as htstore and uuid
    pg_dump --no-privileges --no-owner --schema-only --clean \
        --username "${b_user}" --no-password --host "${b_host}" --port "${b_port}" \
        -f ./"${b_db}".schema.drop.sql "${b_db}" >&2
    echo ./"${b_db}".schema.drop.sql

    pg_dump --no-privileges --no-owner --schema-only \
        --username "${b_user}" --no-password --host "${b_host}" --port "${b_port}" \
        -f ./"${b_db}".schema.sql "${b_db}" >&2
    echo ./"${b_db}".schema.sql

    pg_dump --no-privileges --no-owner --data-only \
        --username "${b_user}" --no-password --host "${b_host}" --port "${b_port}" \
        -f ./"${b_db}".data.sql "${b_db}" >&2
    echo ./"${b_db}".data.sql
); }

# fn_pg_dump_full() { (
#     b_user="${1}"
#     b_host="${2}"
#     b_port="${3}"
#     b_db="${4}"

#     pg_dump --no-privileges --no-owner \
#         --username "${b_user}" --no-password \
#         -f ./"${b_user}".full.sql "${b_user}" >&2
# ); }

# fn_pg_dumpall() { (
#     b_user="${1}"
#     b_host="${2}"
#     b_port="${3}"
#     b_db="${4}"

#     pg_dumpall --no-privileges --globals-only \
#         --username "${b_user}" --no-password --host "${b_host}" --port "${b_port}" \
#         -f ./"${b_user}".globals.sql --dbname "${b_db}" >&2
# ); }

main() { (
    case ${1:-} in
        --help | help)
            fn_help
            return 0
            ;;
        -V | --version | version)
            fn_help
            return 0
            ;;
        "")
            fn_help >&2
            return 1
            ;;
        *) ;;
    esac

    b_pguser="${1:-}"
    b_pghost="${2:-localhost}"
    b_pgport="${3:-5432}"
    b_pgdb="${4:-$b_pguser}"

    fn_pg_dump_parts "${b_pguser}" "${b_pghost}" "${b_pgport}" "${b_pgdb}"
); }

main "${@:-}"
